### ISSUE TITLE
Team 10: Player can send empty chat message

### ISSUE THREAD

**Issue by srfarnsworth** [byucs340ta/Winter2019#109]
Player can send empty chat message, which results in a tiny empty chat bubble in the chat window.

![FireShot Capture 033 - Ticket Denied - ticket-denied jacobbaldwin com](https://user-images.githubusercontent.com/7768540/55367434-3745b700-54aa-11e9-9bbe-409e0ebc745d.png)

**Comment by Jacob-Baldwin** [comment]
Fixed on merge [#101](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/101).
