### ISSUE TITLE
Team 10: History is out of order

### ISSUE THREAD

**Issue by srfarnsworth** [byucs340ta/Winter2019#111]
History is out of order. See image.

![FireShot Capture 034 - Ticket Denied - ticket-denied jacobbaldwin com](https://user-images.githubusercontent.com/7768540/55367520-c18e1b00-54aa-11e9-9cf3-18d231e92f9b.png)

**Comment by Jacob-Baldwin** [comment]
We're going to tackle this if we have time during phase 4. As of right now that is the actual order that commands are being sent it. We'll put this on hold for now though.
