### ISSUE TITLE
Team 10: Player can draw from empty train card deck

### ISSUE THREAD

**Issue by srfarnsworth** [byucs340ta/Winter2019#113]
Player can draw from empty train card deck, but get no cards. After drawing from the empty deck again, player's turn is over. Player should not be allowed to draw from an empty deck. Attached image shows how drawing from empty deck twice results in turn changing to next player but no card was received.

![FireShot Capture 035 - Ticket Denied - ticket-denied jacobbaldwin com](https://user-images.githubusercontent.com/7768540/55367812-11b9ad00-54ac-11e9-97ad-7e83d2158cef.png)

**Comment by Jacob-Baldwin** [comment]
Resolved in merge request [#98](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/98).
