### ISSUE TITLE
Team 10: Train deck has cards, but no face-up train cards show

### ISSUE THREAD

**Issue by srfarnsworth** [byucs340ta/Winter2019#115]
Steps to reproduce:
1. Draw all train cards so there are no face-up cards left.
2. Claim a route so train cards are discarded.
3. Draw train card from deck.

Player gets train cards from deck as expected. However, there should be face-up cards showing as well. Image shows cards in deck, but no face-up cards.

![FireShot Capture 037 - Ticket Denied - ticket-denied jacobbaldwin com](https://user-images.githubusercontent.com/7768540/55368046-1df23a00-54ad-11e9-9b24-29d57f3f105f.png)

**Comment by GeenDutchman** [comment]
Duplicate of issue #7

**Comment by Jacob-Baldwin** [comment]
Resolved in merge [#121](https://gitlab.com/ticket-denied/ticket-denied-server/merge_requests/121).
