### ISSUE TITLE
Some routes not showing up as claimed

### ISSUE THREAD

**Issue by nbarlow23** [byucs340ta/Winter2019#122]
A few of the short routes (Houston to New Orleans and Las Vegas to Los angeles were the only ones I found) can be claimed (you lose cards, gain points, lose train pieces, your turn advances, and no one else can claim it) however no line is drawn on the board, so it doesn't seem to be claimed

**Comment by bajensen** [comment]
![image](https://user-images.githubusercontent.com/11206160/55375342-01fc9180-54c9-11e9-8026-f6ed9633fe18.png)

**Comment by nbarlow23** [comment]
Also El Paso to OKC

**Comment by jtam2** [comment]
@jtam2
