### ISSUE TITLE
Team 14: 3 Face-Up Locomotive Cards

### ISSUE THREAD

**Issue by bajensen** [byucs340ta/Winter2019#124]
If only 5 train cards remain and 3 are locomotives, the app crashes

**Comment by cgilbertut** [comment]
This happened to me but I think it also happened when there was still cards in the deck. Another time one of the games had all locomotives and other had different cards (wasn't able to reproduce). This was the error that came up.
![bug](https://user-images.githubusercontent.com/32402292/55439712-b1397700-5562-11e9-863e-98d31f6773c6.PNG)

**Comment by jtam2** [comment]
@benso1

**Comment by jarinbj** [comment]
fixed so that if it is impossible to discard and replace face up cards until there are less than 3 locomotives the game just keeps 3 locomotives
