### ISSUE TITLE
Team 34: Game Ended after three train pieces used

### ISSUE THREAD

**Issue by grahamd880** [byucs340ta/Winter2019#13]
Game ended message popped up after one turn.
![team34_map](https://user-images.githubusercontent.com/32367607/55354497-246bbc00-5483-11e9-9241-047233888089.png)

**Comment by grahamd880** [comment]
Update: It is after a player uses at least three train pieces that the final round state starts. This is linked to the chat stopping when the final round messages pops up.

**Comment by grahamd880** [comment]
This might be because the game is only initialized with 5 train car pieces per player.

**Comment by lincoln-b** [comment]
Jake

**Comment by bourbon02** [comment]
resolved

**Comment by bourbon02** [comment]
fixed
