### ISSUE TITLE
Team 14 - Claiming Routes w/ Locomotives

### ISSUE THREAD

**Issue by nbarlow23** [byucs340ta/Winter2019#168]
I tried to claim a gray route of length 3. I had 2 of same color (yellow I think) and 1 Locomotive. If you click the locomotive card to try to claim it, it gives the message "Not enough cards, will attempt to use locomotives", claims the route, gives you the points and advances the turns, but it doesn't take away your cards. I still had the locomotive and the 2 yellows. This happens anytime you try to claim a route and click the locomotive card if you have some locomotives and some other cards, but not enough locomotives to claim the whole thing.

**Comment by nbarlow23** [comment]
It actually seems that even if you have enough locomotives, whenever you click locomotives to claim the route, it never decrements them.

**Comment by jtam2** [comment]
@jtam2
