### ISSUE TITLE
5+ Players in One Game

### ISSUE THREAD

**Issue by JonesEri07** [byucs340ta/Winter2019#228]
On launch screen with 6 players registered and logged in.
I initially put four players into the same game.
On the fifth device I click on the game with four players and the confirmation prompt pops up. I DO NOT click anything yet.
On the sixth device I click on the same game (still shows only 4 players joined) the confirmation prompt also pops up on this device.
With both confirmation prompts displaying on devices 5 and 6 I click yes on device 5 and then quickly click yes on device 6 as well.
Result: I have a game with 6 players inside of it.
![6players](https://user-images.githubusercontent.com/37893421/55441350-c2d14d80-5567-11e9-93df-a9ef173ab31d.png)

**Comment by JonesEri07** [comment]
Once the game has been started. Initialization works fine, but then it is no ones turn so the game is unplayable.

**Comment by EskeletoInd** [comment]
Fixed. Thxs
