### ISSUE TITLE
Team 26: drawing destination cards does not always decrease deck size

### ISSUE THREAD

**Issue by jaromweatherford** [byucs340ta/Winter2019#257]
When the destination deck gets small (around 9), drawing destination cards stops reducing the deck size as expected.  Keeping 3 cards each turn lead to deck sizes as follows: 24, 21, 18, 15, 12, 9, 7, 6, 6, 6, 6.  By returning some of the cards the number started going down again, but the amount by which the deck size decreases seems to be related to the number of cards returned in the previous turn rather than the number kept in the current turn.

**Comment by machupicchu2014** [comment]
eric

**Comment by machupicchu2014** [comment]
fixed
