### ISSUE TITLE
Team 26: Purchasing a double route

### ISSUE THREAD

**Issue by zackshorts** [byucs340ta/Winter2019#277]
When trying to purchase the second half of a double route where the first half was already claimed, you are not actually able to claim the second route(Which is good because there were less than 4 players). However, it still switches turns after that and the player that tried to claim the second half of the double route is now stuck in the 'take turn' mode, but can't actually do anything.

**Comment by machupicchu2014** [comment]
matthew

**Comment by machupicchu2014** [comment]
Fixed.
