### ISSUE TITLE
Both players can claim the same route

### ISSUE THREAD

**Issue by EskeletoInd** [byucs340ta/Winter2019#308]
I claimed the same route (Salt Lake City -> Helena) on both clients. Also there doesn't seem to be any visual notification that a route is claimed. I also claimed that route again with the same player again. I was also unable to claim seattle -> Helena and I haven't claimed that with another player or anything weird.
![double route](https://user-images.githubusercontent.com/44655192/55448741-37b38000-5586-11e9-83c4-859befffb1ca.png)

**Comment by SpencerHastings** [comment]
Fixed, thanks!
