### ISSUE TITLE
Game doesn't end if a player has undiscarded destination cards?

### ISSUE THREAD

**Issue by machupicchu2014** [byucs340ta/Winter2019#310]
It seems that the end game condition doesn't get activated if a player hasn't yet discarded their destination cards.

**Comment by zackshorts** [comment]
I don't think you should end the game before that player's turn is over.

**Comment by machupicchu2014** [comment]
I agree that you shouldn't be able to, but the way your game was implemented, a user doesn't have to discard their cards before the turn switches to the next player. So then, we hit a point where the game should have probably ended, but since they have yet to discard their cards, it keeps going (and I think players could keep taking turns?) We weren't super sure if that's what was happening (we only saw it once), but maybe it's worth looking at?
