### ISSUE TITLE
Draw Deck says it has cards but I ran out of faceup cards

### ISSUE THREAD

**Issue by EskeletoInd** [byucs340ta/Winter2019#311]
Both clients say that I have 34 train cards to draw but face up cards stopped reappearing after I draw one card. Continuing to draw lead to an empty sideboard. 
![draw deck](https://user-images.githubusercontent.com/44655192/55448863-aabcf680-5586-11e9-909c-1d0fe6fbbe1e.png)

**Comment by SpencerHastings** [comment]
Fixed, thanks!
