### ISSUE TITLE
Player can claim both routes in doubled route

### ISSUE THREAD

**Issue by KT-EB** [byucs340ta/Winter2019#319]
Problem: if a player has already claimed one of a pair of routes, they can also claim the other route
Reproduce: Claim the right route between Dallas and Little Rock.  On your next turn (when you have the right cards), claim the left route between Dallas and Little Rock.  You will own both routes, but should only be able to own one.

**Comment by Jacob-Baldwin** [comment]
Fixed on merge [#104](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/104).
