### ISSUE TITLE
Doesn't always give points for completed routes

### ISSUE THREAD

**Issue by btc36** [byucs340ta/Winter2019#32]
I completed the destination card Santa Fe to Chicago. I completed it through the following routes:
Santa Fe- Denver
Denver to Kansas City : Black route (Not orange)
Kansas City to Omaha (Left side)
Omaha to Chicago
I DID NOT GET ANY POINTS FOR THIS

**Comment by samecrowder** [comment]
did you complete the game?

**Comment by btc36** [comment]
Yeah, this is based on the Game Over screen

**Comment by samecrowder** [comment]
Fixed
