### ISSUE TITLE
Doubled routes claimed in 3- player game

### ISSUE THREAD

**Issue by KT-EB** [byucs340ta/Winter2019#320]
Problem: both routes of a pair of routes can be claimed even when there are only 2 or 3 players
Reproduce: have two players in a game.  Have one claim a route from Houston to Dallas and have the other claim the other route from Houston to Dallas.

**Comment by Jacob-Baldwin** [comment]
Fixed on merge [#104](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/104).
