### ISSUE TITLE
Claiming a six-train route takes all cards

### ISSUE THREAD

**Issue by KT-EB** [byucs340ta/Winter2019#322]
Problem: when claiming a six-car route, if the player elects to use no wild cards, then all of their cards of that color are spent, even if they had more than six cards of that color
Reproduce: have 9 green cards in your hand.  Claim the route from El Paso to Houston, using 0 rainbow cards.  You should still have 3 green cards left, but will instead have 0

**Comment by KT-EB** [comment]
This issue only happens with colored routes.  Wild routes behave properly.

**Comment by Jacob-Baldwin** [comment]
Fixed by zed on merge [#102](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/102).
