### ISSUE TITLE
Train cars can go into negatives

### ISSUE THREAD

**Issue by KT-EB** [byucs340ta/Winter2019#323]
Problem: claiming a route that costs more train cars than the player has results in the player claiming the route and having negative train cars instead of the player being unable to claim the route
Reproduce: have four train cars and claim a five-car or six-car route.  The player will claim it and have negative train cars, which should not be allowed

**Comment by Jacob-Baldwin** [comment]
Fixed on merge [#103](https://gitlab.com/ticket-denied/ticket-denied-client/merge_requests/103).
