### ISSUE TITLE
Initializing game bugs

### ISSUE THREAD

**Issue by Caledrith** [byucs340ta/Winter2019#328]
Map and destination card selection doesn't display on Mac OS X running Nexus 10 emulator. Number of train is 102 and destination is 24, which doesn't seem quite right. Clicking the action button causes a crash.

**Comment by mpage21** [comment]
I don't know if we will be able to reproduce this since none of us use a Mac.

**Comment by joseluisalarcon** [comment]
Mac functionality not intended --CLOSING--
