### ISSUE TITLE
Team 26: Empty Card Deck Fatal Error

### ISSUE THREAD

**Issue by christian-caldwell** [byucs340ta/Winter2019#337]
Drawing from the deck when the deck has no cards causes the game to throw a popup displaying a loading circle and the string “yo wait ok?” This pop-up will remain on the screen indefinitely and forces the game to terminate.

**Comment by machupicchu2014** [comment]
eric and matthew

**Comment by machupicchu2014** [comment]
It no longer sits on the loading screen forever, though it's still weird.

**Comment by machupicchu2014** [comment]
there.
