### ISSUE TITLE
Team 26: Ticket Card Deck Reshuffle Unreachable

### ISSUE THREAD

**Issue by christian-caldwell** [byucs340ta/Winter2019#338]
The ticket deck is supposed to re-add the cards in the discard pile upon reshuffle. This reshuffle occurs only when 3 or more rainbow cards are visible in the face up set or when the Ticket Deck Count reaches 0. Neither of these states are currently functioning, so I was unable to test the Reshuffle functionality.

**Comment by machupicchu2014** [comment]
Eric

**Comment by machupicchu2014** [comment]
well you can reach it at least when there are three faceup locomotive cards.
