### ISSUE TITLE
Destination cards not updating hand, claim route allowed before destination cards are claimed

### ISSUE THREAD

**Issue by michaeleastwood** [byucs340ta/Winter2019#339]
After drawing the first set of Destination cards for every user, only the first users hand was updated with new Destination cards. The handling of turns allowed for a user to claim a route before he even was assigned their first set of destination cards.

**Comment by coyRocks3** [comment]
Claiming a route resolved

**Comment by coyRocks3** [comment]
Destination card bug resolved
