### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by semagnum** [byucs340ta/Winter2019#37]
1. when claiming a route, a name that takes two lines overflows the label area it's in
2. destination cards are big - having many of them can make scrolling a bit much
3. I didn't know the gauntlet was wild card.  Maybe add a (wild card) to the label?
4. limit message size - I could paste a whole body of HTML.  Just to hinder trolls :)

**Comment by jaydenmilne** [comment]
1. OK
2. We like having the map. Wontfix
3. The manual we provided makes this clear. Wontfix
4. We consider this a feature :) Wontfix. To clarify, you can't inject HTML, there is just no limit to the length of a message

**Comment by semagnum** [comment]
For 2, I never said to remove the map.  I'm just considering reorganizing the area to be a different layout to be easier to view and scroll through (say, vertical scroll with a few per row).
For 3, regardless of the manual's existence, we can't assume everyone that plays reads the manual (how often do we read the terms of use for programs we install?  haha)  Yes, we didn't read the manual; I'm fine with admitting that.  Even among my other team members with experience in Ticket to Ride, we were all confused to understand what each "shard" color/type compared to in the original.  It's up to you to decide if that aspect of the design is a concern.
For 4, yes, it's just the message length limit.  Another concern with that is the fact that the game history is in the same screen.  It can be a hindrance to scroll past "The Bee Movie" just to see what the last person did for their turn ;)  If you split the two, it wouldn't be as much of an issue.

Again, it's all UX: they're not necessarily things that are broken.  It's just considerations based on what a user needs with given circumstances.  How you deal with those concerns is up to you :)

**Comment by jaydenmilne** [comment]
Fixed No 1
