### ISSUE TITLE
Remakes train card deck once empty

### ISSUE THREAD

**Issue by semagnum** [byucs340ta/Winter2019#52]
Can still claim more cards once the deck is empty.

**Comment by semagnum** [comment]
In another game, we ended up having 73 cards in the deck suddenly.

**Comment by jaydenmilne** [comment]
Is this just the reshuffling the discard pile?

**Comment by semagnum** [comment]
Yeah, probably.  I couldn't remember what it was that was off about it.

**Comment by brennonbrimhall** [comment]
Pretty sure here that this is expected behavior; this is the way the rules say to handle no more train cards being available.  Do you have an example of a rule that suggests that what you've indicated should be expected behavior?

**Comment by semagnum** [comment]
I mean that the reshuffling is correct behavior.  I misunderstood the context.  I guess make sure that you can't draw cards if it still says zero (reshuffle before doing so).  I may be wrong about the bug's existence; I apologize if that's the case.

**Comment by jaydenmilne** [comment]
We haven't been able to reproduce this, and we're fairly certain this is working as intended
