### ISSUE TITLE
Team 36: Images not loading

### ISSUE THREAD

**Issue by jeremypleb** [byucs340ta/Winter2019#66]
The images are slow to load sometimes, and so drawing faceup train cards is difficult (don't  know which card is which). The decks don't refresh so there is always a broken image there, if it doesn't load initially.

**Comment by jaydenmilne** [comment]
Try this with good wifi, the room we were in has poor internet

**Comment by jaydenmilne** [comment]
I've had Chrome throttle the internet to "Slow 3G" and while it would take a second for the images to pop in, they always would

**Comment by brennonbrimhall** [comment]
Closing because we can't reproduce.

**Comment by jaydenmilne** [comment]
We did observe this, but it only happened when it took 15+ seconds to load a ~10 kb SVG file. We are prepared to accept slow loading when you have sub dial up internet speeds.
