### ISSUE TITLE
Group 36

### ISSUE THREAD

**Issue by ClintonMcCardell** [byucs340ta/Winter2019#77]
multiple destination ticket screens up between turns

**Comment by jaydenmilne** [comment]
Clicking the deck twice very quickly

**Comment by jaydenmilne** [comment]
Haven't been able to repro this one yet, even with throttled internet

**Comment by ClintonMcCardell** [comment]
This happened in the failed server state (a game was started after the first game has ended)

**Comment by jaydenmilne** [comment]
Yup, we figured that out

**Comment by jaydenmilne** [comment]
Fixed
