### ISSUE TITLE
Disposing of the correct train cards

### ISSUE THREAD

**Issue by lincoln-b** [byucs340ta/Winter2019#84]
Had 3 violet cards and 3 wild cards, claimed a 3 violet route from SF to LA, and it took my 3 wilds, instead of taking the 3 violet cards. I felt scammed. This may be optional as far as the spec is concerned.

**Comment by grahamd880** [comment]
The routes were switched on the server so it wasn't matching the client. The pink route on the client was matching to the yellow route on the server, hence why the wilds were taken instead. I fixed the issue and checked the rest of the double routes as well.
