### ISSUE TITLE
DOUBLE route has some issue when trying to claim

### ISSUE THREAD

**Issue by lincoln-b** [byucs340ta/Winter2019#87]
Player one claimed black route from denver to kansas city, but then it would not let player two claim the orange route from denver to kansas city. In other words, the DOUBLE route has some issue when trying to claim.

**Comment by grahamd880** [comment]
Couldn't replicate the issue with any of the double routes. I specifically checked this case though. I tried five times and was successful in claiming black route denver->kansas for player 1 then claiming orange route from denver->kansas for player 2
